"""Email Sender module for sending job application reports."""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
from config.settings import settings
from utils.logger import logger

async def send_email_with_report(recipient_email: str, file_path: str) -> bool:
    """Send job application report to the candidate's email."""
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_password = os.getenv("SMTP_PASSWORD", "")

    if not smtp_user or not smtp_password:
        logger.warning("SMTP credentials not configured in .env. Cannot send email report.")
        return False

    try:
        msg = MIMEMultipart()
        msg["From"] = smtp_user
        msg["To"] = recipient_email
        msg["Subject"] = "🤖 Job Agent — Daily Job Application Report"

        body = (
            "Hello,\n\n"
            "Please find attached your daily job application report generated by the Autonomous Job Agent.\n\n"
            "It contains two tabs:\n"
            "1. Redirected: Listings skipped because they link to an external career site/ATS.\n"
            "2. Failed Applications: Listings where internal form-filling encountered errors.\n\n"
            "Best regards,\n"
            "Your Job Agent 🤖"
        )
        msg.attach(MIMEText(body, "plain"))

        if os.path.exists(file_path):
            with open(file_path, "rb") as attachment:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename={os.path.basename(file_path)}",
                )
                msg.attach(part)
        else:
            logger.error(f"Email attachment file not found: {file_path}")
            return False

        # Execute SMTP call synchronously in a non-blocking way
        import asyncio
        loop = asyncio.get_event_loop()
        def _send():
            server = smtplib.SMTP(smtp_host, smtp_port)
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.sendmail(smtp_user, recipient_email, msg.as_string())
            server.close()

        await loop.run_in_executor(None, _send)
        logger.success(f"Email report successfully sent to {recipient_email}")
        
        # Delete local Excel report after sending
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
                logger.info(f"Deleted local Excel report {file_path} after email sent.")
            except Exception as delete_err:
                logger.warning(f"Could not delete local Excel report: {delete_err}")
                
        return True
    except Exception as e:
        logger.error(f"Failed to send email report: {e}")
        return False
